export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const FETCH_USER_INFO_START = 'FETCH_USER_INFO_START'
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS'
export const FETCH_USER_INFO_FAIL = 'FETCH_USER_INFO_FAIL'
export const NEW_USER_START = 'NEW_USER_START'
export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS'
export const NEW_USER_FAIL = 'NEW_USER_FAIL'
export const SET_USER_INFO = 'SET_USER_INFO'
/* TO DO
export const AUTH_REFRESH
*/

export const ADD_INGREDIENT_START = 'ADD_INGREDIENT_START'
export const ADD_INGREDIENT_SUCCESS = 'ADD_INGREDIENT_SUCCESS'
export const ADD_INGREDIENT_FAIL = 'ADD_INGREDIENT_FAIL'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'

export const ADD_COCKTAIL_START = 'ADD_COCKTAIL_START'
export const ADD_COCKTAIL_SUCCESS = 'ADD_COCKTAIL_SUCCESS'
export const ADD_COCKTAIL_FAIL = 'ADD_COCKTAIL_FAIL'
export const EDIT_COCKTAIL = 'EDIT_COCKTAIL'
export const REMOVE_COCKTAIL = 'REMOVE_COCKTAIL'
export const SET_COCKTAILS = 'SET_COCKTAILS'
export const FETCH_COCKTAILS_FAILED = 'FETCH_COCKTAILS_FAILED'

export const ADD_TO_STACK = 'ADD_TO_STACK'
export const REMOVE_FROM_STACK = 'REMOVE_FROM_STACK'
export const START_FLASHCARD = 'START_FLASHCARD'
export const VIEWER_CLOSED = 'VIEWER_CLOSED'
export const INCREMENT_FLASHCARD_INDEX = 'INCREMENT_FLASHCARD_INDEX'
export const MANAGE_STACK = 'MANAGE_STACK'